# Generated by Django 4.1.7 on 2023-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(choices=[('Male', True), ('Female', False)])),
            ],
        ),
    ]
