# Generated by Django 4.1.7 on 2023-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')]),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
