# Generated by Django 4.1.7 on 2023-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
