# Generated by Django 4.1.7 on 2023-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_time_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='interaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
