# Generated by Django 4.1.7 on 2023-04-02 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_interaction_time_patient_pick_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dispatch_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 6, 51, 18, 458762)),
            preserve_default=False,
        ),
    ]
