# Generated by Django 4.1.7 on 2023-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_dispatch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='TAT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
