# Generated by Django 4.1.7 on 2023-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='TAT',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True),
        ),
    ]
