# Generated by Django 4.1.7 on 2023-04-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='TAT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
